### ISSUE TITLE
New Function Features, tuple unpacking

### ISSUE THREAD

**Issue by asarkar** [rockthejvm/scala-3-new-features#1]
It seems tuple unpacking doesn't work for nested tuples.
```
def f(x: (Int, Int)) = x(0) + x(1)
List((1, 2), (3, 4)).map(f) // ok
List((1, (2, 3)), (3, (4, 5))).map((a, (b, c)) => a + f(b, c)) // not ok
```

Error:
```
) expected but => found
not a legal formal parameter for a function literal
Not found: b
Not found: c
```

**Comment by daniel-ciocirlan** [comment]
That's expected - if you want to destructure your nested tuple on the spot, you'll need to write a partial function (see the advanced course), like this:

```
List((1, (2, 3)), (3, (4, 5))).map {
  case (a, (b, c)) => a + f(b, c)
}
```

closing as it's not an issue with the repo or the course

**Comment by asarkar** [comment]
This is an issue with the compiler. It’s really weird for unpacking to work for a simple case and not work for others. I’ve opened a ticket on against Dotty.

https://github.com/lampepfl/dotty/issues/19311
